In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()
X= iris.data
y= iris.target
feature_names=iris.feature_names
target_names = iris.target_names

print("Feature names:", feature_names)
print("Target name:", target_names)
print("\n First 10 rows of x: \n",X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target name: ['setosa' 'versicolor' 'virginica']

 First 10 rows of x: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [6]:
from sklearn.model_selection import train_test_split

X_train,X_text,y_train,y_test = train_test_split(X,y, test_size=0.3, random_state=42)

print(X_train.shape)
print(X_text.shape)
print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)
